-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "esMX")
if not L then return end

--@localization(locale="esMX", format="lua_additive_table", table-name="L", handle-unlocalized="comment")@
